REM    BAS_NOW.bas, 2015-02-21
REM    THE FIRST PROGRAM STDUIED BY KEREMY AND KURTZ
REM    OF DARTMOUTH, WAS NOT "HELLO WORLD!"
REM NOW DAYS IS BASIC FASTER THAN A SPREADSHEET SOLUTION???????
5 LET AGAIN$="NO"
PRINT "    AX + BY = C"
PRINT "    DX + EY = F"
PRINT "    SOLUTION: X= (CE-BF)/(AE-BD)" 
PRINT "              Y= (AF-CD)/(AE-BD)"
PRINT "              WHEN (AE-BD) <> 0"
PRINT
INPUT "A = ",A
INPUT "B = ",B
INPUT "C = ",C
INPUT "D = ",D
INPUT "E = ",E
INPUT "F = ",F
PRINT
LET G=A*E-B*D
IF G=0 THEN PRINT "NO UNIQUE SOLUTION"
IF G=0 THEN PRINT
IF G=0 THEN INPUT "TO TRY AGAIN JUST PRESS ENTER, ANY KEY +ENTER TO QUIT ",AGAIN$
IF G=0 AND LEN(AGAIN$)=0 THEN CLS
IF G=0 AND LEN(AGAIN$)=0 THEN GOTO 5
IF G=0 AND LEN(AGAIN$) THEN END
LET X=(C*E-B*F)/G
LET Y=(A*F-C*D)/G
PRINT "X = ";X;"     ";"Y = ";Y
PRINT
INPUT "TO TRY AGAIN JUST PRESS ENTER, ANY KEY +ENTER TO QUIT ",AGAIN$
IF LEN(AGAIN$)=0 THEN CLS
IF LEN(AGAIN$)=0 THEN GOTO 5
IF LEN(AGAIN$) THEN END


