
'FULL SCREEN LAVA.BAS SMALLBASIC 0.12.0 2015-11-18 MGA/B+
'MANY MODIFICATIONS TO LAVA FROM THE CODE LIBRARY

DM=500
DIM CX(1 TO DM),CY(1 TO DM),CC(1 TO DM),COLR(100)
RANDOMIZE TIMER
FOR I=0 TO 100
  R=RND
  IF I MOD 3=0 THEN 
    COLR(I)=RGB(0,0,0) 
  ELIF I MOD 3=1 
    COLR(I)=RGB(R*255,0,0)
  ELSE 
    COLR(I)=RGB(R*127+128,R*127+64,0)
  FI
NEXT
FOR K = 1 TO DM
  CX(K) = INT(RND*XMAX)
  CY(K) = INT(RND*YMAX)
  CC(K)=COLR(INT(RND*41))
NEXT K     
REPEAT
  RECT 0,0,XMAX,YMAX,0
  PAINT INT(RND*(XMAX-2))+1,INT(RND*(YMAX-2))+1, COLR(INT(RND*101)),0
  FOR K=1 TO DM
    CIRCLE CX(K),CY(K),RND*8+2,RND*.6,CC(K) FILLED
    CX(K)=CX(K)+INT(RND*6)
    IF CX(K)>XMAX-10 THEN CX(K)=10
    CY(K)=CY(K)+INT(RND*9)-4
    IF CY(K)<5 OR CY(K)>YMAX-5 THEN CY(K)=RND*(YMAX-10)+5:CX(K)=10
  NEXT K
  SHOWPAGE
UNTIL LEN(INKEY$)
